### ISSUE TITLE
Tree algorithms

### ISSUE THREAD

**Issue by jsmatthews** [jsmatthews/Algorithms#3]
### Binary Trees
- [ ] Depth-first Search: In-order
- [ ] Depth-first Search: Pre-order
- [ ] Depth-first Search: Post-order
- [ ] Breadth-first Search
- [ ] TreeSort

### Heaps
- [ ] HeapSort
- [ ] SmoothSort
- [ ] TournamentSort
